server.port: 8085

api:
  finnhub:
    token: 'ck46ck1r01qus81pqgegck46ck1r01qus81pqgf0'
    domain: 'finnhub.io'
    base-url: 'api/v1'
    endpoints:
      stock:
        indicator: '/indicator'
        profile2: '/stock/profile2'
        quote: '/quote'
        all: '/stock/symbol'
  holiday:
    domain: 'date.nager.at'
    base-url: 'api/v3'
    endpoint: '/PublicHolidays'

spring.datasource:
  #driverClassName: 'org.hibernate.dialect.PostgreSQLDialect'
  #driverClassName: 'org.h2.Driver'
  driverClassName: 'org.postgresql.Driver'
  #url: 'jdbc:h2:mem:jpademo'
  #username: 'sa'
  #password: 
  url: 'jdbc:postgresql://localhost:5432/postgres'
  username: 'postgres'
  password: 'A35675465'
spring:
  h2:
    console:
      enabled: true

management.endpoints.web.base-path: /data
management.endpoints.web.exposure.include: "*"
web.exposure.include: beans, mappings
management.endpoint.health.group.readiness.show-details: always

        
info.application:
  name: "HelloWorld"
  description: "A Demo for Spring Boot hello World"
  author:
    name: "Vincent Cheung"
    bio: "Testing Bio"
    
    

  

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update
  #properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  # properties.hibernate.dialect: org.h2.Driver
  # Hibernate ddl auto (create, create-drop, validate, update)
spring.data.redis:
  host: localhost
  port: 6379

spring.sql.init:
  mode: always # always
  platform: h2
  #schema-locations: classpath:ddl/DDL_DROPS.sql, classpath:ddl/DDL_TUSERS.sql, classpath:ddl/DDL_TPOSTS.sql

spring.profiles.active: enableScheduling