server.port: 8086


api:
  Finnhub:
    token: 'ck4fhrpr01qus81pv2ogck4fhrpr01qus81pv2p0'
    domain: 'finnhub.io'
    stockEndpoint: '/api/v1/stock/profile2'
    quoteEndpoint: '/api/v1/quote'

spring.datasource:
  url: 'jdbc:postgresql://localhost:5432/postgres'
  username: 'postgres'
  password: 'A35675465'
spring.jpa:
  show-sql: true
  ##Hibernate Properties
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  ##Hibernate ddl auto(create, create-drop, validate, update)
  hibernate.ddl-auto: validate # update

spring.sql.init:
  mode: always