server.port: 8086

spring.datasource:
  driverClassName: 'org.postgresql.Driver' 
  url: 'jdbc:postgresql://localhost:5432/postgres'
  username: 'postgres'
  password: 'A35675465'
spring:
  h2:
    console:
      enabled: true

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update 

spring.sql.init:
  mode: always # always
  platform: h2


